[package]
name = "cmot"
version = "0.1.0"
authors = ["Bret Copeland <bret@atlantisflight.org>"]

[dependencies]
failure = "0.1.1"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.4", features = ["consoleapi", "handleapi", "processenv", "winbase", "wincon"] }
